site_name: Exemplar-based Inpainting
repo_url: https://bitbucket.org/coronis-computing/exemplar_based_inpainting
repo_name: exemplar_based_inpainting
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
theme:
  name: material
  language: en
  logo: resources/coronis_logo_web.png
  favicon: resources/coronis_favicon_32x32.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # features:
  #   - navigation.indexes
  #   - navigation.tabs
  #   - navigation.instant
  #   - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
  - meta
plugins:
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - search:
      lang: en  
  - mkdocstrings
extra:
  version:
    provider: mike
  social:
    - icon: material/email
      link: "mailto:ricard.campos@coronis.es"
